# Generated by Django 4.2.11 on 2024-04-28 15:39

from django.db import migrations, models
import shopping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('bracelet', 'Bracelet'), ('chakra_stone', 'Chakra Stone'), ('incence', 'Incense'), ('natural_stone', 'Natural Stone'), ('pendulum', 'Pendulum'), ('none', 'None')], max_length=255)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('img', models.ImageField(upload_to=shopping.models.get_image_upload_path)),
            ],
        ),
    ]
