# Generated by Django 4.2.11 on 2024-04-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_cartproduct_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
