# Generated by Django 4.2.11 on 2024-04-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
    ]
