# Generated by Django 4.2.11 on 2024-05-30 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='The date and time the comment was created.', verbose_name='Created On')),
                ('author', models.ForeignKey(help_text='Comment creator', on_delete=django.db.models.deletion.PROTECT, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment Creator')),
                ('post', models.ForeignKey(help_text='Select the post to which this comment will be associated.', on_delete=django.db.models.deletion.PROTECT, related_name='post_comments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-created_on',),
            },
        ),
    ]
