# Generated by Django 4.2.11 on 2024-08-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='images/default_image.png', null=True, upload_to='posts'),
        ),
    ]
