# Generated by Django 4.2.11 on 2024-04-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_alter_cart_items_alter_cart_shipping_and_more'),
        ('user', '0004_remove_profile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.cart'),
        ),
    ]
