# Generated by Django 4.2.11 on 2024-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_alter_cart_items_alter_cart_shipping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='shopping.cartproduct'),
        ),
    ]
