# Generated by Django 4.2.11 on 2024-08-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
