# Generated by Django 4.2.11 on 2024-08-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
