# Generated by Django 4.2.11 on 2024-08-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_ratings', to='order.order'),
            preserve_default=False,
        ),
    ]
